
jobs:
  include:
  - language: bash
    os: linux
    dist: trusty
    services: docker
    script:
    - docker run -v $PWD:/src -w /src crystallang/crystal:0.31.1 crystal spec
  - language: bash
    os: linux
    dist: trusty
    services: docker
    script:
    - docker run -v $PWD:/src -w /src crystallang/crystal:1.0.0 crystal spec


  #crystal:
  #- latest
  #- nightly
  #- 0.35.1
  #- 1.0.0

